// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApi.Data;

#nullable disable

namespace QuizApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240922141437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizApi.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TimeTaken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("QuizApi.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("QuestionInWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = 2,
                            Option1 = "Hyper Trainer Marking Language",
                            Option2 = "Hyper Text Marketing Language",
                            Option3 = "Hyper Text Markup Language",
                            Option4 = "Hyper Text Markup Leveler",
                            QuestionInWords = "What does HTML stand for?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = 2,
                            Option1 = "ALU",
                            Option2 = "Memory",
                            Option3 = "CPU",
                            Option4 = "Control unit",
                            QuestionInWords = "The brain of any computer system is"
                        },
                        new
                        {
                            Id = 3,
                            Answer = 1,
                            Option1 = "FORTRAN",
                            Option2 = "PROLOG",
                            Option3 = "C",
                            Option4 = "COBOL",
                            QuestionInWords = "Which of the following computer language is used for artificial intelligence?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = 2,
                            Option1 = "Mathematical Mind",
                            Option2 = "Artistic mind",
                            Option3 = "Logical Mind",
                            Option4 = "Scientific Knowledge",
                            QuestionInWords = "What is the primary requisite of a good computer programmer?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = 2,
                            ImageName = "mouse.png",
                            Option1 = "Keyboard",
                            Option2 = "Monitor",
                            Option3 = "Mouse",
                            Option4 = "Graphics Card",
                            QuestionInWords = "Name the device."
                        },
                        new
                        {
                            Id = 6,
                            Answer = 0,
                            Option1 = "Analytical Engine",
                            Option2 = "Calculator",
                            Option3 = "Processor",
                            Option4 = "Abacus",
                            QuestionInWords = "The first mechanical computer designed by Charles Babbage was called ?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = 1,
                            Option1 = "4 bits",
                            Option2 = "8 bits",
                            Option3 = "16 bits",
                            Option4 = "32 bits",
                            QuestionInWords = "One byte is equivalent to ?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = 2,
                            Option1 = "FTP",
                            Option2 = "UML",
                            Option3 = "HTML",
                            Option4 = "URL",
                            QuestionInWords = "Web pages are written using ?"
                        },
                        new
                        {
                            Id = 9,
                            Answer = 3,
                            Option1 = "Dos",
                            Option2 = "Unix",
                            Option3 = "Window NT",
                            Option4 = "CSS",
                            QuestionInWords = "Which of the following is NOT operating system ?"
                        },
                        new
                        {
                            Id = 10,
                            Answer = 3,
                            Option1 = "Interface Program",
                            Option2 = "Interface Protocol",
                            Option3 = "Internet program",
                            Option4 = "Internet Protocol",
                            QuestionInWords = "What is the full form of lP ?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
